# Generated by Django 5.2.5 on 2025-08-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_tasks_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_compeleted',
            new_name='is_completed',
        ),
    ]
